- name: Get config from Cisco IOS devices
  hosts: sw_access
  gather_facts: no

  tasks:
    - name: Get running config
      ios_config:
        backup: yes
        backup_options:
          filename: "{{inventory_hostname}}-backup.cfg"
          dir_path: backup

