- name: "configure interface with ios_config"
  hosts: sw_access
  become: yes
  gather_facts: false

  tasks:
    - name: configure interface settings
      ios_config:
        lines:
          - description test interface
          - switchport mode access
          - switchport access vlan 1
        parents: interface Fa0/1
